### ISSUE TITLE
Mermaid diagrams extends page limit

### ISSUE THREAD

**Issue by icamps** [DanielFlaum/grav-plugin-mermaid-diagrams#4]
Hello,

I am using Mermaid to add diagrams to my site.

I have a sidebar with other stuff and the diagram is drawn out of the page limits, over the info in the sidebar.

So, I was wondering how to circumvent this. Right now, I have two ideas (but don’t now how to implement them, I don’t even know if it possible).
1-) Remove the sidebar for only that page.
2- Force Mermaid to draw the diagram in the page area.

I am using the Gateway them.

Any ideas?

Regards,

Camps

**Comment by DanielFlaum** [comment]
I'll take a look as soon as I can and get back to you

**Comment by icamps** [comment]
Thank you.

In this link is where I am generated the diagram:
[https://moleculardocking.net/faq/faq-molecular-docking/faq-how-to-start](https://moleculardocking.net/faq/faq-molecular-docking/faq-how-to-start).

**Comment by DanielFlaum** [comment]
OK, so it looks like the simplest solution is to add some CSS to your Grav theme: `svg { max-width: 100%; }`. This will cause the diagram to shrink until it fits correctly, and it will then be following the same behaviour as other images do.

But it may not be the solution you like, because now the diagram is smaller and harder to read. Unfortunately, my plug-in can't (and isn't supposed to) control the actual layout of a diagram--that's the job of Mermaid itself.

One you thing you can try and see if you like as to have the diagram layout from side-to-side instead of top-to-bottom, effectively rotating it 90 degrees. This will cause the diagram to be taller than it is wide, so that it can appear at its natural size.

**Comment by icamps** [comment]
Ok, I will try your suggestions.

Thank you very much.
